### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by xulike666** [stkevintan/lovewallpaper#3]
Uncaught Exception:
TypeError: Cannot read property 'close' of null
    at EventEmitter.ipcMain.on (/Applications/LoveWallpaperHD.app/Contents/Resources/app.asar/main.js:23:42)
    at emitTwo (events.js:111:20)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/Applications/LoveWallpaperHD.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

**Comment by stkevintan** [comment]
Fixed on 2.0.2
